version: '3.7'
services:
  runner-gitlab:
    restart: unless-stopped
    image: gitlab/gitlab-runner:latest
    container_name: gitlab-runner-tic-tac-toegether
    volumes:
      - ./config.toml:/etc/gitlab-runner/config.toml
      - /var/run/docker.sock:/var/run/docker.sock